Update ruuner-config.yml

diff --git a/ruuner-config.yml b/ruuner-config.yml
--- a/ruuner-config.yml
+++ b/ruuner-config.yml
@@ -11,13 +11,17 @@
     ami_id: ami-084568db4383264d4  
     TOKEN: "{{ TOKEN }}"
     user_data: |
-      #!/bin/bash
-      sudo -u ubuntu mkdir actions-runner && cd actions-runner
-      sudo -u ubuntu curl -o actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
-      sudo -u ubuntu echo "0dbc9bf5a58620fc52cb6cc0448abcca964a8d74b5f39773b7afcad9ab691e19  actions-runner-linux-x64-2.323.0.tar.gz" | shasum -a 256 -c
-      sudo -u ubuntu tar xzf ./actions-runner-linux-x64-2.323.0.tar.gz
-      sudo -u ubuntu ./config.sh --url https://github.com/chandirasoodan/git_actions --token "{{ TOKEN }}"
-      sudo -u ubuntu ./run.sh
+        #!/bin/bash
+        set -e  # Exit immediately if a command fails
+        sudo -u ubuntu bash <<EOF
+        mkdir -p ~/actions-runner && cd ~/actions-runner
+        curl -o actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
+        echo "0dbc9bf5a58620fc52cb6cc0448abcca964a8d74b5f39773b7afcad9ab691e19  actions-runner-linux-x64-2.323.0.tar.gz" | shasum -a 256 -c
+        tar xzf ./actions-runner-linux-x64-2.323.0.tar.gz
+        ./config.sh --url https://github.com/chandirasoodan/git_actions --token "{{ TOKEN }}" --name "runner-$(hostname)" --work ~/actions-runner
+        chmod +x ./run.sh
+        ./run.sh &
+        EOF
   tasks:       
     - name: Ensure correct Python interpreter
       ansible.builtin.command: /opt/pipx/venvs/ansible-core/bin/python -m pip install botocore boto3
